version: "3"

services:
  db:
    image: postgres:15
    environment:
      DB_NAME: ${DB_NAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./database/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  data_insertion:
    environment:
      DB_USER: ${DB_USER}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      CSV_PATH: ${CSV_PATH}
    build:
      context: ./
      dockerfile: database/data_insertion/data_insertion.dockerfile
      args:
        KAGGLE_USR: ${KAGGLE_USR}
        KAGGLE_TOKEN: ${KAGGLE_TOKEN}
    depends_on:
      - db
  api:
    build:
      context: ./
      dockerfile: app/docker/api.dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
      - data_insertion
    environment:
      DB_USER: ${DB_USER}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./app/logs:/logs

volumes:
  pgdata:

